This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./tesi.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file tesi.acn....done (58 entries accepted, 0 rejected).
Sorting entries....done (367 comparisons).
Generating output file tesi.acr....done (54 lines written, 0 warnings).
Output written in tesi.acr.
Transcript written in tesi.alg.
